### ISSUE TITLE
Wappalyzer extension sometimes doesn't show any data

### ISSUE THREAD

**Issue by jahtomini** [wappalyzer/wappalyzer#6863] opened 2022-10-14 16:46 UTC
**Platform**
Which platform does the bug apply to?
* WebExtension (Google Chrome)

**Describe the bug**
If a website is opened in one tab and left open while a different site is opened in another tab, going back to the first website sometime later (approximately 10 minutes) and clicking on the Wappalyzer extension will lead to a 'No technologies detected.' message shown in the popover however upon reloading it shows the technologies perfectly fine.

**To Reproduce**
1. Go to any website. I tested this on [twitter.com](https://twitter.com), [fauna.com](https://fauna.com), [edgedb.com](https://edgedb.com), and [getbootstrap.com](https://getbootstrap.com) but I'm sure it can be replicated on all sites. __Don't click on the Wappalyzer extension.__
2. Leave that tab open and go to any other website(s) and don't go back to the first website for up to 10 minutes
3. Finally go back to the initial website and click on the Wappalyzer extension
4. Receive the message No technologies detected.'

**Expected behavior**
Clicking the extension should display the technologies detected.

**Additional context**
This only began when updated to the latest version (6.10.41) on October 13 2022

**Comment by zloirock** [comment] 2022-10-14 21:29
Chrome 106, macOS 12.6, Wappalyzer 6.10.41

![image](https://user-images.githubusercontent.com/2213682/195946632-344ec66b-901a-4ba3-b31b-93069777a1a4.png)

After a click, with a big chance (>50%):

![image](https://user-images.githubusercontent.com/2213682/195946672-2e978bd6-b94b-4842-a1aa-f0b2b6240f72.png)

After a page reloading, with a big chance, all works fine:

![image](https://user-images.githubusercontent.com/2213682/195946746-dfb8232b-6a2c-4393-86cc-058dd10325a8.png)

**Comment by jahtomini** [comment] 2022-10-14 23:57
> Chrome 106, macOS 12.6, Wappalyzer 6.10.41
> 
> ![image](https://user-images.githubusercontent.com/2213682/195946632-344ec66b-901a-4ba3-b31b-93069777a1a4.png)
> 
> After some seconds, after a click, with a big chance (>50%):
> 
> ![image](https://user-images.githubusercontent.com/2213682/195946672-2e978bd6-b94b-4842-a1aa-f0b2b6240f72.png)
> 
> After a page reloading and an immediate click, with a big chance, all works fine:
> 
> ![image](https://user-images.githubusercontent.com/2213682/195946746-dfb8232b-6a2c-4393-86cc-058dd10325a8.png)

Same exact environment, except I'm on macOS 12.3.1, also installed the new Chrome update to 106 on the same day as I updated Wappalyzer

**Comment by AliasIO** [comment] 2022-10-15 03:42
I've heard about this issue from others but it doesn't happen for me so it's a little hard to debug. The only significant change in v6.10.41 is the switch to Manifest V3 (see 6d3ba54fa9b71909dbc04e1f87998106184c222a) but I'm not sure why that would cause this to happen intermittently.

**Comment by zloirock** [comment] 2022-10-15 03:44
As an option, it can be related to the latest (106.0.5249.119) Chrome that was updated almost at the same time with Wappalyzer.

**Comment by zloirock** [comment] 2022-10-15 03:46
I can try to load the old Wappalyzer version, but maybe after a day or two.

**Comment by AliasIO** [comment] 2022-10-15 04:00
Never mind, deadefbcc96ff60ca8e7084c722b0d76724a8002 fixes the issue. `chrome.storage.sync` doesn't handle large objects, causing `QUOTA_BYTES_PER_ITEM` errors. Reverting to `chrome.storage.local` solves it. Pushing an update now.

**Comment by rainzee** [comment] 2022-10-15 16:48
I have same issue

**Comment by AliasIO** [comment] 2022-10-17 22:07
Is anyone still having issues on v6.10.42?

**Comment by jahtomini** [comment] 2022-10-17 22:38
> Is anyone still having issues on v6.10.42?

Yep, got the update but still not fixed unfortunately

**Comment by zloirock** [comment] 2022-10-17 22:41
Yes, it's still an issue in 6.10.42.

**Comment by AliasIO** [comment] 2022-10-17 22:51
Weirdly it's not happening for me.

Could you do me a favour and install the extension [from source](https://github.com/wappalyzer/wappalyzer#chrome-extension)?

Please go to chrome://extensions and see if there are any errors, and click 'Inspect views' -> 'service worker' to check for any errors in the console.

<img width="549" alt="Screenshot 2022-10-18 at 9 48 24 am" src="https://user-images.githubusercontent.com/77259/196297999-1ad76169-68a0-422a-bebb-3962b8dd423a.png">

Another thing to try is to click the 'clear cached detections' button in the extension settings.

When changing any settings in the extension, do they persist?

**Comment by zloirock** [comment] 2022-10-17 23:14
At first glance, the extension built from the source works fine.

**Comment by AliasIO** [comment] 2022-10-17 23:40
Thanks! The `not ready for sendMessage` and `Extension context invalidated` errors are probably not the issue, is the second `Uncaught (in promise) [object Object]` error related to that from what you can see?

**Comment by zloirock** [comment] 2022-10-17 23:48
![image](https://user-images.githubusercontent.com/2213682/196304024-781f033f-73cb-4bda-9d8f-99d07eb007ef.png)

**Comment by zloirock** [comment] 2022-10-17 23:52
One more:

![image](https://user-images.githubusercontent.com/2213682/196304345-f425a367-1e98-4ecd-b17b-d684bd61a5b7.png)

**Comment by AliasIO** [comment] 2022-10-18 00:29
Please pull the latest (d149dbc3722327e09c149c358a6bf8d521dc8930) and try again?

**Comment by zloirock** [comment] 2022-10-18 00:33
Still the same.

**Comment by AliasIO** [comment] 2022-10-19 00:07
This should be fixed now. I realised that with Manifest V3, Chrome kills the background service worker every few minutes and the identified technologies are wiped from memory.

**Comment by zloirock** [comment] 2022-10-19 00:17
5 minutes without this issue - so it looks like it's really fixed.

**Comment by jahtomini** [comment] 2022-10-19 19:29
Looks like it's finally fixed, we should be able to close this issue now

**Comment by jahtomini** [comment] 2022-10-27 14:19
Looks like it's back 😞, but this time it doesn't even show any technologies at all. So it's literally not working at least for me on the latest v6.10.44. 

Chrome 106, macOS 12.3.1, Wappalyzer 6.10.44

**Comment by AliasIO** [comment] 2022-10-27 20:13
@jahtomini Could you follow [these steps](https://github.com/wappalyzer/wappalyzer/issues/6863#issuecomment-1281600102) to see if there's any errors? Have you tried re-installing the extension?

**Comment by zloirock** [comment] 2022-10-28 03:10
In my case, *almost* everything works fine. After some hours / days randomly, rare enough, it can show no technologies, in what cases - I can not understand.

**Comment by rainzee** [comment] 2022-10-28 05:31
Still shows nothing

**Comment by AliasIO** [comment] 2022-10-29 00:39
The changes in 1df71527a310009b94b5209f0c3c7bffc4641141 should hopefully fix the random empty popup that occurs after several hours.

**Closed** 2022-11-06 21:56 UTC
Labels: Bug

**Comment by zloirock** [comment] 2023-01-03 17:43
@AliasIO apparently, this problem is back.

**Comment by AliasIO** [comment] 2023-01-03 23:47
@zloirock The cache is kept around for 100 hostnames for 2 days, are you exceeding one of those?

https://github.com/wappalyzer/wappalyzer/blob/master/src/drivers/webextension/js/driver.js#L15

**Comment by zloirock** [comment] 2023-01-03 23:52
Now it shows results only in the first seconds. In most cases, after some tenths seconds - empty results.

![image](https://user-images.githubusercontent.com/2213682/210460174-181287d6-599a-4dcf-817f-e69be92cff48.png)

**Comment by zloirock** [comment] 2023-01-03 23:55
Wappalyzer 6.10.53, Chrome 108.0.5359.124, caching is disabled in the settings.

**Comment by AliasIO** [comment] 2023-01-04 00:31
You may get weird behaviour when you don't show cached results as it will only show results on the last page you visited on the domain and the results will disappear after some inactivity. The cache is essential with the Manifest V3 version as the background service gets killed often, wiping memory.

**Comment by zloirock** [comment] 2023-01-04 00:36
Hmm, that worked fine for a long time with a disabled cache.

**Comment by zloirock** [comment] 2023-01-04 00:39
After enabling it's still a problem - but in fewer cases.

**Comment by zloirock** [comment] 2023-01-04 01:05
![image](https://user-images.githubusercontent.com/2213682/210465960-b580d928-80c1-4c93-bd67-cd6d3ee9e872.png)

**Comment by AliasIO** [comment] 2023-01-04 02:31
It's weird because the caching logic hasn't been touched the last few versions.

I can reproduce it (with cache disabled) by opening a web page (e.g. twitter.com) and chrome://extensions, removing focus from Chrome and waiting a few seconds for the service worker to die:

<img width="423" alt="Screenshot 2023-01-04 at 1 22 32 pm" src="https://user-images.githubusercontent.com/77259/210473007-4f266572-e350-43df-b212-8b9fba57d4c5.png">

Now when you click the extension on the web page, it'll be empty because the memory is gone (as expected). If you're using Chrome actively the memory may stick around for longer.

The error you shared is due to the service worker getting killed during while a message is being sent.

Can you try clearing the detection cache in the extension settings to see if that helps?

**Comment by zloirock** [comment] 2023-01-04 12:26
After cache clearing and restarting the extension and the browser, no problems so far. Let's see what will be later.

**Comment by zloirock** [comment] 2023-01-10 16:47
That still happens periodically with enabled cache.
