### ISSUE TITLE
Technology doe not render - Refused to execute script from 'https://www.wappalyzer.com/_nuxt/static/1680742604/manifest.js' 

### ISSUE THREAD

**Issue by nuno** [wappalyzer/wappalyzer#7623] opened 2023-04-15 17:59 UTC
**Platform**
Which platform does the bug apply to?
* WebExtension
 -  Google Chrome (Version 112.0.5615.121) - "Wappalyzer - Technology profiler 6.10.62" -> https://chrome.google.com/webstore/detail/wappalyzer-technology-pro/gppongmhjkpfnbhagpmjfkannfbllamg -
 - Firefox (Version: 112.0 (64-bit))  - "Wappalyzer  6.10.56" -> https://addons.mozilla.org/en-US/firefox/addon/wappalyzer/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser
* Website: all sites, no one in particular

**Describe the bug**
I haven't been able to see the technology for about a week after clicking on one from the list via the chrome extension. 
This issue happens on all sites, not one in particular, does not render the tech, only blinks and shows when the site loads for the first time for 1 second, then disappear.

**To Reproduce**
1. Go to any website: ex https://www.speedtest.net/
2. Click on wappalyzer extension and pick for example backbone.js
3. wappalyzer site loads
4. See error -
````
CONSOLE ERROR
Refused to execute script from 'https://www.wappalyzer.com/_nuxt/static/1680742604/manifest.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
c @ 24d5dd2.js:1
e2661fa.js:1 TypeError: Cannot read properties of undefined (reading 'length')
    at f.<anonymous> (6097f64.js:1:25785)
    at t._render (e2661fa.js:1:40585)
    at f.r (e2661fa.js:1:70982)
    at t.get (e2661fa.js:1:20843)
    at new t (e2661fa.js:1:20756)
    at t (e2661fa.js:1:70996)
    at ur.$mount (e2661fa.js:1:71214)
    at init (e2661fa.js:1:25774)
    at n (e2661fa.js:1:29736)
    at e2661fa.js:1:58918

CONSOLE WARNING
The resource https://www.wappalyzer.com/_nuxt/static/1680742604/technologies/javascript-libraries/lodash/payload.js 
was preloaded using link preload but not used within a few seconds from the window's load event. 
Please make sure it has an appropriate `as` value and it is preloaded intentionally.

````

 ![Screenshot 2023-04-15 at 18 03 08](https://user-images.githubusercontent.com/38348/232244178-835f5967-f206-4610-990f-94474a139608.png)

**Expected behavior**
I want be able to see the tech that I clicked: example if I click backbone from this list ( see image )
![Screenshot 2023-04-15 at 18 34 47](https://user-images.githubusercontent.com/38348/232244567-a9efcac9-324b-4dcd-a088-b7dab880410c.png)

 
**Additional context**
What I've already tried to do so far:
1 - I removed and reinstalled the extension via chrome store -> https://chrome.google.com/webstore/detail/wappalyzer-technology-pro/gppongmhjkpfnbhagpmjfkannfbllamg

2- I tried clearing the browser's data and cache

3- I tried to clear the cache of the website itself -> https://www.wappalyzer.com/

4- I disabled all extensions leaving only the wappalyzer extension

5 - I restarted the chrome browser (Version 112.0.5615.121 (Official Build) (arm64))
   and the computer: "macos Monterey 12.6.4" - m1

I tried to search for an issue like this but I could not found. If this is some kind of duplicate please move it to the correct place.

**Comment by AliasIO** [comment] 2023-04-23 21:27
Thanks, I think this is fixed now. You may need do a hard refresh (Cmd+Shift+R or Ctrl+Shift+R) once, after that pages should load correctly.

**Comment by mesosoi** [comment] 2023-05-01 18:38
> Thanks, I think this is fixed now. You may need do a hard refresh (Cmd+Shift+R or Ctrl+Shift+R) once, after that pages should load correctly.

I have a similar issue: the page I open renders but swiftly disappears. I use Firefox 114.0 if that means anything.

**Comment by nuno** [comment] 2023-05-05 15:47
> Thanks, I think this is fixed now. You may need do a hard refresh (Cmd+Shift+R or Ctrl+Shift+R) once, after that pages should load correctly.

It works ok for me now. Thank you!

**Comment by a1ternat1ve** [comment] 2023-06-16 17:48
Same here, Hard Refresh didn't work for me...

**Comment by AliasIO** [comment] 2023-07-04 22:55
@a1ternat1ve Mind trying it again? The `manifest.js` file that seems to causing the issue isn't actually needed so I removed it.

**Comment by a1ternat1ve** [comment] 2023-07-04 23:20
> @a1ternat1ve Mind trying it again? The `manifest.js` file that seems to causing the issue isn't actually needed so I removed it.

@AliasIO Works correctly now, thanks!

**Closed** 2023-07-04 23:28 UTC
Labels: Bug
