### ISSUE TITLE
Garbage in Google Analytics value

### ISSUE THREAD

**Issue by lelas** [wappalyzer/wappalyzer#7430] opened 2023-02-14 00:42 UTC
**Platform**
Which platform does the bug apply to?

NPM

**Describe the bug**
For the technology `Google Analytics`, Wappalyzer sometimes returns a crazy amount of redundant information/markup. In the attached example the result for this single site amounts to 3230 KB of data.

**To Reproduce**
1. Identify technologies on raider.io (my version is attached) with the npm package while processing multiple URLs in parallel. You can also try wordpress.com (less garbage, but quite a bit still).
2. Scroll down to 'Google Analytics' and check the value in key `Value`.

**Expected behavior**
A result for Google Analytics consisting of a short string.

[wappalyzer-bug_raider_io.zip](https://github.com/wappalyzer/wappalyzer/files/10727448/wappalyzer-bug_raider_io.zip)

**Comment by lelas** [comment] 2023-02-14 13:40
I edited the issue to reflect that we only get garbage data returned in the `value` field for `Google Analytics` when we process multiple URLs in parallel.

**Comment by AliasIO** [comment] 2023-02-27 00:59
The ZIP file appears to be empty but I could reproduce this using the `--extend` option. The `value` field contains the string that was matched, which in the case of `scripts` can be the entire contents of a JavaScript file. It's supposed to omit this value when the contents are long, which didn't work correctly because the value is an array instead of a string. Fixed in a03077dcf8c4d01e933a0c4d4c1eb7be08fb6f4d.

**Closed by AliasIO** 2023-02-27 00:59 UTC
Labels: Bug
